#!/usr/bin/env node
/**
 * nello-claw bootstrap - renders the wizard bundle into a live installation.
 *
 * Input: ./bundle.json (or NC_BUNDLE env path) - wizard answers JSON
 * Output: personalised files written into the install dir (CWD)
 *
 * Steps:
 *   1. Render CLAUDE.md, AGENTS.md, .mcp.json, claude_desktop_config.json, plist
 *   2. Seed the vault preset into the target vault path
 *   3. Symlink bundled skills into ~/.claude/skills/
 *   4. Merge settings.json into ~/.claude/settings.json
 *   5. If morningBrief enabled, register the cron task
 *   6. If service enabled and macOS, install + load LaunchAgent
 *   7. Run audit at the end
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync, symlinkSync, unlinkSync, lstatSync, copyFileSync, readdirSync, chmodSync } from 'node:fs'
import { join, dirname, basename } from 'node:path'
import { homedir } from 'node:os'
import { execSync, spawnSync } from 'node:child_process'
import Handlebars from 'handlebars'

const TEMPLATE_DIR = dirname(new URL(import.meta.url).pathname)
const INSTALL_PATH = process.env.NC_INSTALL_PATH || process.cwd()
const BUNDLE_PATH = process.env.NC_BUNDLE || join(INSTALL_PATH, 'bundle.json')

// Sandbox overrides - tests use these to isolate from production ~/.claude.
// SETTINGS_PATH defaults to PROJECT-SCOPED settings inside the install dir, NOT global.
// This means bypassPermissions only applies when Claude is working in ~/nello-claw/.
const SETTINGS_PATH = process.env.NC_SETTINGS_PATH || join(INSTALL_PATH, '.claude', 'settings.json')
const SKILLS_DIR = process.env.NC_SKILLS_DIR || join(homedir(), '.claude', 'skills')
const LAUNCHAGENT_LABEL = process.env.NC_LAUNCHAGENT_LABEL || 'com.nello-claw.server'

// Theme: FFA600 accent via 24-bit truecolour. Falls back gracefully on plain terminals.
const ACCENT = '\x1b[38;2;255;166;0m'
const WHITE = '\x1b[38;2;255;255;255m'
const RED = '\x1b[38;2;255;80;80m'
const DIM = '\x1b[2m', RESET = '\x1b[0m'
const ok = (m) => console.log(`  ${ACCENT}✓${RESET} ${m}`)
const warn = (m) => console.log(`  ${ACCENT}!${RESET} ${m}`)
const fail = (m) => console.log(`  ${RED}✗${RESET} ${m}`)
const info = (m) => console.log(`\n${ACCENT}→${RESET} ${WHITE}${m}${RESET}`)

// Handlebars helpers
Handlebars.registerHelper('eq', (a, b) => a === b)
Handlebars.registerHelper('or', (...args) => args.slice(0, -1).some(v => !!v))
Handlebars.registerHelper('and', (...args) => args.slice(0, -1).every(v => !!v))
Handlebars.registerHelper('slug', (s) => String(s).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''))
Handlebars.registerHelper('today', () => new Date().toISOString().slice(0, 10))

function renderTemplate(srcHbs, destPath, ctx) {
  const raw = readFileSync(srcHbs, 'utf-8')
  const out = Handlebars.compile(raw, { noEscape: true })(ctx)
  mkdirSync(dirname(destPath), { recursive: true })
  writeFileSync(destPath, out, 'utf-8')
}

function buildContext(bundle) {
  const escapedPath = INSTALL_PATH.replace(/^\//, '-').replace(/\//g, '-')
  return {
    ...bundle,
    installPath: INSTALL_PATH,
    escapedPath,
    home: homedir(),
    nodePath: process.execPath,
    today: new Date().toISOString().slice(0, 10),
    vaultPath: bundle.vaultPath || join(INSTALL_PATH, 'vault'),
    env: bundle.keys || {},
    mcps: bundle.mcps || {},
  }
}

function writeEnv(bundle) {
  const keys = bundle.keys || {}
  const lines = [
    '# Auto-generated by nello-claw bootstrap',
    `# ${new Date().toISOString()}`,
    '',
  ]
  for (const [k, v] of Object.entries(keys)) {
    if (v === null || v === undefined || v === '') continue
    const escaped = String(v).includes(' ') || String(v).includes('#') ? `"${v}"` : v
    lines.push(`${k}=${escaped}`)
  }
  lines.push('')
  lines.push(`VAULT_PATH=${bundle.vaultPath || join(INSTALL_PATH, 'vault')}`)
  const envPath = join(INSTALL_PATH, '.env')
  writeFileSync(envPath, lines.join('\n'))
  try { chmodSync(envPath, 0o600) } catch {}
}

function symlinkSkills() {
  const src = join(TEMPLATE_DIR, 'skills')
  const dest = SKILLS_DIR
  mkdirSync(dest, { recursive: true })

  for (const name of readdirSync(src)) {
    const srcPath = join(src, name)
    const destPath = join(dest, name)
    if (existsSync(destPath)) {
      try {
        const stat = lstatSync(destPath)
        if (stat.isSymbolicLink()) {
          unlinkSync(destPath)
        } else {
          // Back up existing dir
          const bak = `${destPath}.bak-${Date.now()}`
          execSync(`mv "${destPath}" "${bak}"`)
          warn(`backed up existing skill to ${basename(bak)}`)
        }
      } catch {}
    }
    symlinkSync(srcPath, destPath)
  }
  ok(`linked ${readdirSync(src).length} skills into ~/.claude/skills/`)
}

function mergeSettingsJson(ctx) {
  const settingsPath = SETTINGS_PATH
  mkdirSync(dirname(settingsPath), { recursive: true })

  const newSettings = JSON.parse(Handlebars.compile(
    readFileSync(join(TEMPLATE_DIR, 'hooks', 'settings.json.hbs'), 'utf-8'),
    { noEscape: true }
  )(ctx))

  let existing = {}
  if (existsSync(settingsPath)) {
    try { existing = JSON.parse(readFileSync(settingsPath, 'utf-8')) } catch {}
    copyFileSync(settingsPath, `${settingsPath}.bak-${Date.now()}`)
  }

  const merged = { ...existing, ...newSettings }
  merged.hooks = { ...(existing.hooks || {}), ...newSettings.hooks }
  merged.enabledPlugins = { ...(existing.enabledPlugins || {}), ...newSettings.enabledPlugins }
  merged.extraKnownMarketplaces = { ...(existing.extraKnownMarketplaces || {}), ...newSettings.extraKnownMarketplaces }

  writeFileSync(settingsPath, JSON.stringify(merged, null, 2))
  ok(`wrote project-scoped settings: ${settingsPath}`)
}

function installService() {
  // Cross-platform: delegates to scripts/install-service.js (Mac launchctl / Win schtasks / Linux systemd)
  const res = spawnSync('node', [join(TEMPLATE_DIR, 'scripts', 'install-service.js')], {
    env: {
      ...process.env,
      NC_INSTALL_PATH: INSTALL_PATH,
      NC_LAUNCHAGENT_LABEL: LAUNCHAGENT_LABEL,
    },
    stdio: 'inherit',
  })
  if (res.status !== 0) fail(`service install failed (exit ${res.status})`)
}

function seedMorningBrief(bundle) {
  if (!bundle.enableMorningBrief) return
  const prompt = bundle.morningBriefPrompt || 'Morning brief: what matters today?'
  const cron = bundle.morningBriefCron || '0 9 * * *'
  const chatId = (bundle.keys?.ALLOWED_CHAT_ID ?? '').split(',')[0]?.trim()
  if (!chatId) { warn('morning brief skipped (no chat id yet)'); return }

  const res = spawnSync('node', [
    join(TEMPLATE_DIR, 'packages', 'scheduler', 'dist', 'register-morning-brief.js'),
  ], {
    env: { ...process.env, MORNING_BRIEF_PROMPT: prompt, MORNING_BRIEF_CRON: cron, ALLOWED_CHAT_ID: chatId, NC_INSTALL_PATH: INSTALL_PATH },
    stdio: 'inherit',
  })
  if (res.status === 0) ok(`morning brief registered (${cron})`)
  else warn('morning brief registration failed')
}

const BANNER = `
${ACCENT}
 ███╗   ██╗███████╗██╗     ██╗      ██████╗
 ████╗  ██║██╔════╝██║     ██║     ██╔═══██╗
 ██╔██╗ ██║█████╗  ██║     ██║     ██║   ██║  ${RESET}${DIM}claw${RESET}${ACCENT}
 ██║╚██╗██║██╔══╝  ██║     ██║     ██║   ██║
 ██║ ╚████║███████╗███████╗███████╗╚██████╔╝
 ╚═╝  ╚═══╝╚══════╝╚══════╝╚══════╝ ╚═════╝
${RESET}
`

async function main() {
  console.log(BANNER)

  if (!existsSync(BUNDLE_PATH)) {
    fail(`bundle not found at ${BUNDLE_PATH}`)
    process.exit(1)
  }

  const bundle = JSON.parse(readFileSync(BUNDLE_PATH, 'utf-8'))
  const ctx = buildContext(bundle)

  // Upfront summary so user (and Claude in plan mode) sees every change before any of them happen.
  console.log(`${ACCENT}This bootstrap will make these changes:${RESET}`)
  console.log(`  ${DIM}1.${RESET} Write personalised files to ${INSTALL_PATH}/ (CLAUDE.md, AGENTS.md, .env, .mcp.json, vault/)`)
  console.log(`  ${DIM}2.${RESET} chmod 600 on ${INSTALL_PATH}/.env so only you can read it`)
  console.log(`  ${DIM}3.${RESET} Symlink ${readdirSync(join(TEMPLATE_DIR, 'skills')).length} bundled skills into ${SKILLS_DIR} (existing skills with same names get .bak'd)`)
  console.log(`  ${DIM}4.${RESET} Write project-scoped settings to ${SETTINGS_PATH}`)
  console.log(`     ${DIM}(this enables bypassPermissions ONLY when working in this folder, NOT globally)${RESET}`)
  console.log(`  ${DIM}5.${RESET} Install obsidian-cli globally via npm (lets Claude write vault notes from CLI)`)
  console.log(`  ${DIM}6.${RESET} Create vault/Memory/ + vault/Journal/ - your assistant auto-saves notes here as Obsidian markdown`)
  if (bundle.installLaunchAgent) {
    console.log(`  ${DIM}7.${RESET} Register auto-start service "${LAUNCHAGENT_LABEL}" via launchctl/schtasks/systemd`)
  }
  if (bundle.enableMorningBrief) {
    console.log(`  ${DIM}8.${RESET} Seed daily morning-brief task in store/clawd.db`)
  }
  console.log(`  ${DIM}*.${RESET} Bundle file at ${BUNDLE_PATH} is NOT deleted automatically - you delete it after\n`)

  info('Writing personalised files')
  renderTemplate(join(TEMPLATE_DIR, 'CLAUDE.md.hbs'), join(INSTALL_PATH, 'CLAUDE.md'), ctx)
  renderTemplate(join(TEMPLATE_DIR, 'AGENTS.md.hbs'), join(INSTALL_PATH, 'AGENTS.md'), ctx)
  renderTemplate(join(TEMPLATE_DIR, 'brain-context.md.hbs'), join(INSTALL_PATH, 'brain-context.md'), ctx)
  renderTemplate(join(TEMPLATE_DIR, '.mcp.json.hbs'), join(INSTALL_PATH, '.mcp.json'), ctx)
  renderTemplate(join(TEMPLATE_DIR, 'claude_desktop_config.json.hbs'), join(INSTALL_PATH, 'claude_desktop_config.json'), ctx)
  writeEnv(bundle)
  ok('CLAUDE.md, AGENTS.md, brain-context.md, .env, .mcp.json, claude_desktop_config.json')

  info('Seeding vault')
  const { seedVault } = await import('./packages/vault-seeder/dist/seed.js')
  const seedResult = seedVault({
    preset: bundle.vaultPreset || 'nello',
    vaultPath: ctx.vaultPath,
    presetsRoot: join(TEMPLATE_DIR, 'vault-presets'),
    bundle: ctx,
  })
  ok(`vault seeded (${seedResult.written.length} files, ${seedResult.skipped.length} skipped)`)

  info('Linking skill pack + merging settings.json')
  symlinkSkills()
  mergeSettingsJson(ctx)

  info('Creating runtime dirs')
  mkdirSync(join(INSTALL_PATH, 'store'), { recursive: true })
  mkdirSync(join(INSTALL_PATH, 'workspace', 'uploads'), { recursive: true })
  // Vault is the memory. Memory + Journal subdirs live inside the vault
  // so Obsidian indexes them via graph + full-text search.
  mkdirSync(join(ctx.vaultPath, 'Memory'), { recursive: true })
  mkdirSync(join(ctx.vaultPath, 'Journal'), { recursive: true })
  ok('store/, workspace/uploads/, vault/Memory/, vault/Journal/')

  info('Installing obsidian-cli (vault commands for Claude)')
  try {
    execSync('npm install -g obsidian-cli', { stdio: 'pipe' })
    ok('obsidian-cli installed globally')
  } catch (err) {
    warn(`obsidian-cli install failed (${err.message?.split('\n')[0] || 'unknown'}). Vault still works as plain markdown.`)
  }

  if (bundle.installLaunchAgent) {
    info('Installing auto-start service')
    installService()
  }

  if (bundle.enableMorningBrief) {
    info('Seeding morning brief')
    seedMorningBrief(bundle)
  }

  info('Audit')
  try {
    execSync(`node "${join(TEMPLATE_DIR, 'packages', 'audit', 'dist', 'cli.js')}" audit`, {
      stdio: 'inherit',
      env: { ...process.env, NC_INSTALL_PATH: INSTALL_PATH },
    })
  } catch {}

  // Bundle still has plaintext keys. Tell the user, don't auto-delete.
  // Auto-delete looks like covering tracks; explicit deletion is safer + clearer.
  console.log(`\n${ACCENT}Done.${RESET}\n`)
  console.log(`Your keys are now in ${INSTALL_PATH}/.env (chmod 600).`)
  console.log(`The original bundle still has plaintext copies. ${ACCENT}Delete it now:${RESET}`)
  console.log(`  ${DIM}rm "${BUNDLE_PATH}"${RESET}\n`)
  console.log(`Next:`)
  console.log(`  cd ${INSTALL_PATH}`)
  console.log(`  claude                       ${DIM}# open Claude Code here${RESET}`)
  console.log(`  open http://localhost:3000   ${DIM}# web dashboard${RESET}`)
  console.log(`  ${DIM}your vault auto-opens in Obsidian${RESET}\n`)
}

main().catch((err) => {
  fail(err.stack || err.message)
  process.exit(1)
})
