#!/usr/bin/env node
/**
 * Cross-platform service installer.
 * Mac:   launchctl + plist
 * Win:   Task Scheduler + schtasks
 * Linux: systemd user service
 *
 * Reads NC_INSTALL_PATH + NC_LAUNCHAGENT_LABEL from env.
 * Idempotent - safe to rerun.
 */

import { execSync, spawnSync, spawn } from 'node:child_process'
import { writeFileSync, readFileSync, existsSync, mkdirSync, copyFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { homedir, platform } from 'node:os'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const TEMPLATE_DIR = join(__dirname, '..')
const INSTALL = process.env.NC_INSTALL_PATH || join(homedir(), 'nello-claw')
const LABEL = process.env.NC_LAUNCHAGENT_LABEL || 'com.nello-claw.server'
const NODE = process.execPath
// Daemon entry compiled to template/dist/index.js (the @nc/template package
// builds into its own dist/, not the install root). Don't change without also
// fixing template/package.json's build output path.
const ENTRY = join(INSTALL, 'template', 'dist', 'index.js')

const ACCENT = '\x1b[38;2;255;166;0m'
const RED = '\x1b[38;2;255;80;80m'
const RESET = '\x1b[0m'
const ok = (m) => console.log(`  ${ACCENT}✓${RESET} ${m}`)
const fail = (m) => console.log(`  ${RED}✗${RESET} ${m}`)

function installMac() {
  const dest = join(homedir(), 'Library', 'LaunchAgents', `${LABEL}.plist`)
  mkdirSync(dirname(dest), { recursive: true })

  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${LABEL}</string>
    <key>ProgramArguments</key>
    <array>
        <string>${NODE}</string>
        <string>${ENTRY}</string>
    </array>
    <key>WorkingDirectory</key>
    <string>${INSTALL}</string>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>${INSTALL}/store/server.log</string>
    <key>StandardErrorPath</key>
    <string>${INSTALL}/store/server.log</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/opt/homebrew/bin:/usr/local/bin:${homedir()}/.local/bin:/usr/bin:/bin</string>
        <key>HOME</key>
        <string>${homedir()}</string>
        <key>NC_INSTALL_PATH</key>
        <string>${INSTALL}</string>
    </dict>
    <key>ThrottleInterval</key>
    <integer>5</integer>
</dict>
</plist>
`
  writeFileSync(dest, plist)
  const uid = process.getuid?.() ?? 501
  try { execSync(`launchctl bootout gui/${uid}/${LABEL}`, { stdio: 'ignore' }) } catch {}
  try {
    execSync(`launchctl bootstrap gui/${uid} "${dest}"`, { stdio: 'ignore' })
    ok(`LaunchAgent loaded (${LABEL})`)
  } catch (err) {
    fail(`LaunchAgent load failed: ${err.message}`)
    process.exit(1)
  }
}

function installWindows() {
  // Drop a .lnk into the per-user Startup folder. Runs at every interactive
  // logon. Zero admin required (vs schtasks /Create /RL HIGHEST which needs
  // an elevated shell). The .cmd wrapper makes the daemon's stdout+stderr go
  // to store/server.log so we have logs to debug from.
  const wrapper = join(INSTALL, 'nello-claw-daemon.cmd')
  const storeDir = join(INSTALL, 'store')
  const logFile = join(storeDir, 'server.log')
  // Backslashes are valid in cmd.exe paths; quoted paths handle spaces. No JSON-style escaping needed.
  const wrapperContent =
    `@echo off\r\n` +
    `rem nello-claw daemon launcher (auto-generated by install-service.js)\r\n` +
    `cd /d "${INSTALL}"\r\n` +
    `if not exist "${storeDir}" mkdir "${storeDir}"\r\n` +
    `"${NODE}" "${ENTRY}" >> "${logFile}" 2>&1\r\n`
  writeFileSync(wrapper, wrapperContent)

  // Wipe any stale schtasks entry from previous installs (safe if it doesn't exist).
  try { execSync(`schtasks /Delete /F /TN "${LABEL}"`, { stdio: 'ignore' }) } catch {}

  // Drop the startup-folder .lnk. WScript.Shell COM via PowerShell - same
  // pattern as createWindowsShortcuts in bootstrap.js.
  const startup = join(
    process.env.APPDATA || join(homedir(), 'AppData', 'Roaming'),
    'Microsoft', 'Windows', 'Start Menu', 'Programs', 'Startup'
  )
  mkdirSync(startup, { recursive: true })
  const shortcutPath = join(startup, 'nello-claw.lnk')

  const ps = `$ws=New-Object -ComObject WScript.Shell; ` +
    `$s=$ws.CreateShortcut('${shortcutPath.replace(/'/g, "''")}'); ` +
    `$s.TargetPath='${wrapper.replace(/'/g, "''")}'; ` +
    `$s.WorkingDirectory='${INSTALL.replace(/'/g, "''")}'; ` +
    `$s.WindowStyle=7; ` +  // 7 = minimized so it doesn't pop a console window
    `$s.Description='nello-claw daemon (auto-start at login)'; ` +
    `$s.Save();`

  try {
    execSync(`powershell -NoProfile -Command "${ps.replace(/"/g, '\\"')}"`, { stdio: 'pipe' })
    ok(`Startup shortcut created (${shortcutPath})`)
  } catch (err) {
    fail(`Startup shortcut creation failed: ${err.message?.split('\n')[0] || 'unknown'}`)
    process.exit(1)
  }

  // Start the daemon now so the user doesn't have to logout/login first.
  try {
    spawn('cmd', ['/c', 'start', '/min', '""', wrapper], { detached: true, stdio: 'ignore' }).unref()
    ok('daemon started in background')
  } catch {
    ok(`daemon will start on next login (run "${wrapper}" to launch now)`)
  }
}

function installLinux() {
  const dest = join(homedir(), '.config', 'systemd', 'user', `${LABEL}.service`)
  mkdirSync(dirname(dest), { recursive: true })

  const unit = `[Unit]
Description=nello-claw assistant daemon
After=network.target

[Service]
Type=simple
ExecStart=${NODE} ${ENTRY}
WorkingDirectory=${INSTALL}
Environment=NC_INSTALL_PATH=${INSTALL}
Restart=always
RestartSec=5
StandardOutput=append:${INSTALL}/store/server.log
StandardError=append:${INSTALL}/store/server.log

[Install]
WantedBy=default.target
`
  writeFileSync(dest, unit)
  try {
    execSync('systemctl --user daemon-reload', { stdio: 'ignore' })
    execSync(`systemctl --user enable --now ${LABEL}`, { stdio: 'ignore' })
    ok(`systemd user service enabled (${LABEL})`)
  } catch (err) {
    fail(`systemctl failed: ${err.message}. Run 'loginctl enable-linger $USER' if running headless.`)
    process.exit(1)
  }
}

const p = platform()
if (p === 'darwin') installMac()
else if (p === 'win32') installWindows()
else if (p === 'linux') installLinux()
else { fail(`unsupported platform: ${p}`); process.exit(1) }
